{
    'src/frontend/**/*.{js,mjs,cjs,ts,mts,cts}':
        [
            'npx --prefix src/frontend eslint --no-error-on-unmatched-pattern --no-warn-ignored --max-warnings=0 --fix',
            'npx prettier --write',
        ],
    'src/frontend/**/*.scss':
        [
            'npx --prefix src/frontend stylelint --allow-empty-input --max-warnings=0 --fix',
            'npx prettier --write',
        ],
    '*.md': ['npx prettier --write', 'npx tsx docs/utils/transform-md.ts encode'],
    '!(*.{js,mjs,cjs,ts,mts,cts}|*.scss|*.md)': 'npx prettier --ignore-unknown --write',
}
