# docker-compose project name
name: polimerbeton--prod-selinux

services:
    web:
        build:
            context: ./src
            dockerfile: Dockerfile.prod
        image: polimerbeton-web:prod--selinux
        container_name: polimerbeton-web--prod-selinux
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8080 --workers 3
        restart: always
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles:z
        expose:
            - 8080
        env_file:
            - ./env/.env.prod
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:17.6
        container_name: polimerbeton-db--prod-selinux
        restart: always
        env_file:
            - ./env/.env.prod.db
        volumes:
            - postgres_data:/var/lib/postgresql/data/:Z
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 10

    nginx-proxy:
        build:
            context: ./web/nginx-proxy
            dockerfile: Dockerfile.prod
        container_name: nginx-proxy--prod-selinux
        restart: always
        ports:
            - 443:443
            - 80:80
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles:z
            - conf:/etc/nginx/conf.d:z
            - vhost:/etc/nginx/vhost.d:z
            - html:/usr/share/nginx/html:z
            - certs:/etc/nginx/certs:z,ro
            - /var/run/docker.sock:/tmp/docker.sock:z,ro
        depends_on:
            - web

    docker-gen:
        image: nginxproxy/docker-gen:0.15
        container_name: docker-gen--prod-selinux
        restart: always
        command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - ./web/templates/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:Z,ro
            - conf:/etc/nginx/conf.d:z
            - vhost:/etc/nginx/vhost.d:z
            - html:/usr/share/nginx/html:z
            - certs:/etc/nginx/certs:z,ro
            - /var/run/docker.sock:/tmp/docker.sock:z,ro

    acme-companion:
        image: nginxproxy/acme-companion:2.6
        container_name: acme-companion--prod-selinux
        restart: always
        env_file:
            - ./env/.env.prod.proxy-companion
        volumes:
            - conf:/etc/nginx/conf.d:z
            - vhost:/etc/nginx/vhost.d:z
            - html:/usr/share/nginx/html:z
            - certs:/etc/nginx/certs:z,rw
            - acme:/etc/acme.sh:Z
            - /var/run/docker.sock:/var/run/docker.sock:z,ro
        depends_on:
            - nginx-proxy

networks:
    default:
        name: polimerbeton-app-network-prod-selinux

volumes:
    postgres_data:
    static_volume:
    acme:
    certs:
    html:
    vhost:
    conf:
