# docker-compose project name
name: polimerbeton--dev

services:
    app:
        build:
            context: .
            dockerfile: src/Dockerfile
        image: polimerbeton-app:dev
        container_name: polimerbeton-app--dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src/:/root/www/polimerbeton
        ports:
            - 8000:8000
        env_file:
            - ./env/.env.dev
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:18-alpine
        container_name: polimerbeton-db--dev
        restart: always
        env_file:
            - ./env/.env.dev
        volumes:
            - postgres_data:/var/lib/postgresql
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
            interval: 5s
            timeout: 5s
            retries: 10

networks:
    default:
        name: polimerbeton-app-network-dev

volumes:
    postgres_data:
