# Generated by Django 5.2.6 on 2025-09-21 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time of registration for this request'),
        ),
    ]
