# Generated by Django 5.2.6 on 2026-09-30 22:04

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(default='-', verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(default='-', verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(default='-', verbose_name='Phone number'),
        ),
    ]
