# Generated by Django 6.1.1 on 2026-10-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_client_first_name_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='domain',
            field=models.CharField(default='polimerbeton-vrn.ru', max_length=255, verbose_name='Website domain'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='price',
            field=models.DecimalField(decimal_places=2, default=279.0, max_digits=10, verbose_name='Current product price on the website (₽)'),
        ),
    ]
