#? --- Stage 1. Build frontend via Gulp
#? ------------------------------------
FROM node:26.10-slim AS frontend_builder
WORKDIR /usr/src/polimerbeton

# ! --- IMPORTANT !!! | env-переменные для Puppeteer внутри Linux-контейнера
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        python3 \
        python3-pip \
        chromium \
    && pip install --no-cache-dir --break-system-packages foundrytools-cli \
    && rm -rf /var/lib/apt/lists/*

# 1. Кэширование npm-зависимостей
COPY package.json package-lock.json .npmrc ./
COPY src/frontend/package.json ./src/frontend/

# * Флаг --ignore-scripts отключает prepare и postinstall скрипты (husky & md:decode)
RUN npm ci --workspace=src/frontend --ignore-scripts && npm cache clean --force

# 2. Копируем исходный код
COPY src ./src

# 3. Запускаем сборку Gulp
WORKDIR /usr/src/polimerbeton/src/frontend
RUN npm run django -- --verbose

#? --- Stage 2. Install Python Prod-dependencies
#? ---------------------------------------------
FROM python:3.14-slim AS backend_builder
WORKDIR /usr/src/polimerbeton/src/backend

# 1. Настройка переменных окружения для Python
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir poetry
COPY src/backend/pyproject.toml src/backend/poetry.lock ./

# * Установка Python-зависимостей строго БЕЗ dev-пакетов
RUN poetry config virtualenvs.create false \
    && poetry install --no-root --without dev

#? --- Stage 3. Execute "production" scenario
#? ------------------------------------------
FROM python:3.14-slim AS production

# 1. Создаем системного пользователя warden и директории
RUN addgroup --system warden && adduser --system --group warden

ENV HOME=/home/warden \
    APP_HOME=/home/warden/www/polimerbeton

WORKDIR $APP_HOME

# 2. Обновление и установка системных пакетов
RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat-openbsd ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# 3. Забираем скомпилированный Python и зависимости (без dev) из Stage 2
COPY --from=backend_builder /usr/local /usr/local

# 4. Забираем backend с уже собранной статикой из Stage 1
COPY --from=frontend_builder /usr/src/polimerbeton/src/backend $APP_HOME/backend

# 5. Переменные окружения Python
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR $APP_HOME/backend

# 6. Подготовка папки staticfiles, скрипта entrypoint.prod.sh и прав доступа
RUN mkdir -p $APP_HOME/backend/staticfiles \
    && sed -i 's/\r$//g' $APP_HOME/backend/scripts/entrypoint.prod.sh \
    && chmod +x $APP_HOME/backend/scripts/entrypoint.prod.sh \
    && chown -R warden:warden $HOME

# 7. Переключаемся на непривилегированного пользователя
USER warden

# 8. Запуск entrypoint.sh
ENTRYPOINT ["/home/warden/www/polimerbeton/backend/scripts/entrypoint.prod.sh"]
